#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the transmission-daemon package to those
        # expected by OpenMediaVault.
        if [ -z "$2" ]; then
            echo "Updating init script links and actions."
            deb-systemd-helper disable transmission-daemon.service >/dev/null || true
            deb-systemd-invoke stop transmission-daemon.service >/dev/null || true

            # Restart rsyslog to load the provided configuration if rsyslog is
            # installed and enabled since we're not dependent on it. Only needs
            # to be done when the plugin is installed.
            if deb-systemd-helper debian-installed rsyslog.service; then
                if deb-systemd-helper is-enabled rsyslog.service; then
                    deb-systemd-invoke restart rsyslog.service >/dev/null || true
                fi
            fi
        fi

        # Update the configuration.
        SERVICE_XPATH_NAME="transmissionbt"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_node "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_key "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_key "${SERVICE_XPATH}" "cache-size-mb" "4"
            omv_config_add_key "${SERVICE_XPATH}" "dht-enabled" "1"
            omv_config_add_key "${SERVICE_XPATH}" "encryption" "1"
            omv_config_add_key "${SERVICE_XPATH}" "lazy-bitfield-enabled" "1"
            omv_config_add_key "${SERVICE_XPATH}" "lpd-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}" "message-level" "2"
            omv_config_add_key "${SERVICE_XPATH}" "pex-enabled" "1"
            omv_config_add_key "${SERVICE_XPATH}" "scrape-paused-torrents-enabled" "1"
            omv_config_add_key "${SERVICE_XPATH}" "script-torrent-done-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}" "script-torrent-done-filename"
            omv_config_add_key "${SERVICE_XPATH}" "utp-enabled" "1"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules"; then
            omv_config_add_node "${SERVICE_XPATH}" "modules"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/bandwidth"; then
            omv_config_add_node "${SERVICE_XPATH}/modules" "bandwidth"
            omv_config_add_key "${SERVICE_XPATH}/modules/bandwidth" "alt-speed-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/bandwidth" "alt-speed-down" "50"
            omv_config_add_key "${SERVICE_XPATH}/modules/bandwidth" "alt-speed-up" "50"
            omv_config_add_key "${SERVICE_XPATH}/modules/bandwidth" "speed-limit-down" "100"
            omv_config_add_key "${SERVICE_XPATH}/modules/bandwidth" "speed-limit-down-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/bandwidth" "speed-limit-up" "100"
            omv_config_add_key "${SERVICE_XPATH}/modules/bandwidth" "speed-limit-up-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/bandwidth" "upload-slots-per-torrent" "14"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/blocklists"; then
            omv_config_add_node "${SERVICE_XPATH}/modules" "blocklists"
            omv_config_add_key "${SERVICE_XPATH}/modules/blocklists" "blocklist-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/blocklists" "blocklist-sync-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/blocklists" "blocklist-sync-frequency" "daily"
            omv_config_add_key "${SERVICE_XPATH}/modules/blocklists" "blocklist-url" "http://www.example.com/blocklist"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/filesandlocations"; then
            omv_config_add_node "${SERVICE_XPATH}/modules" "filesandlocations"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "download-sharedfolderref"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "download-dir"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "incomplete-sharedfolderref"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "incomplete-dir" "incomplete"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "incomplete-dir-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "preallocation" "1"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "rename-partial-files" "1"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "start-added-torrents" "1"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "trash-original-torrent-files" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "umask" "18"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "watch-sharedfolderref"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "watch-dir" "watch"
            omv_config_add_key "${SERVICE_XPATH}/modules/filesandlocations" "watch-dir-enabled" "0"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/peer"; then
            omv_config_add_node "${SERVICE_XPATH}/modules" "peer"
            omv_config_add_key "${SERVICE_XPATH}/modules/peer" "bind-address-ipv4" "0.0.0.0"
            omv_config_add_key "${SERVICE_XPATH}/modules/peer" "bind-address-ipv6" "::"
            omv_config_add_key "${SERVICE_XPATH}/modules/peer" "peer-limit-global" "240"
            omv_config_add_key "${SERVICE_XPATH}/modules/peer" "peer-limit-per-torrent" "60"
            omv_config_add_key "${SERVICE_XPATH}/modules/peer" "peer-socket-tos" "default"
            omv_config_add_key "${SERVICE_XPATH}/modules/peer" "peer-port" "51413"
            omv_config_add_key "${SERVICE_XPATH}/modules/peer" "peer-port-random-high" "65535"
            omv_config_add_key "${SERVICE_XPATH}/modules/peer" "peer-port-random-low" "1024"
            omv_config_add_key "${SERVICE_XPATH}/modules/peer" "peer-port-random-on-start" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/peer" "port-forwarding-enabled" "1"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/queuing"; then
            omv_config_add_node "${SERVICE_XPATH}/modules" "queuing"
            omv_config_add_key "${SERVICE_XPATH}/modules/queuing" "download-queue-enabled" "1"
            omv_config_add_key "${SERVICE_XPATH}/modules/queuing" "download-queue-size" "5"
            omv_config_add_key "${SERVICE_XPATH}/modules/queuing" "queue-stalled-enabled" "1"
            omv_config_add_key "${SERVICE_XPATH}/modules/queuing" "queue-stalled-minutes" "30"
            omv_config_add_key "${SERVICE_XPATH}/modules/queuing" "seed-queue-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/queuing" "seed-queue-size" "10"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/rpc"; then
            omv_config_add_node "${SERVICE_XPATH}/modules" "rpc"
            omv_config_add_key "${SERVICE_XPATH}/modules/rpc" "rpc-authentication-required" "1"
            omv_config_add_key "${SERVICE_XPATH}/modules/rpc" "rpc-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/rpc" "rpc-password" "openmediavault"
            omv_config_add_key "${SERVICE_XPATH}/modules/rpc" "rpc-port" "9091"
            omv_config_add_key "${SERVICE_XPATH}/modules/rpc" "rpc-username" "admin"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/modules/scheduling"; then
            omv_config_add_node "${SERVICE_XPATH}/modules" "scheduling"
            omv_config_add_key "${SERVICE_XPATH}/modules/scheduling" "alt-speed-time-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/scheduling" "alt-speed-time-begin" "540"
            omv_config_add_key "${SERVICE_XPATH}/modules/scheduling" "alt-speed-time-end" "1020"
            omv_config_add_key "${SERVICE_XPATH}/modules/scheduling" "alt-speed-time-day" "127"
            omv_config_add_key "${SERVICE_XPATH}/modules/scheduling" "idle-seeding-limit" "30"
            omv_config_add_key "${SERVICE_XPATH}/modules/scheduling" "idle-seeding-limit-enabled" "0"
            omv_config_add_key "${SERVICE_XPATH}/modules/scheduling" "ratio-limit" "2.0"
            omv_config_add_key "${SERVICE_XPATH}/modules/scheduling" "ratio-limit-enabled" "0"
        fi

        # Add Zeroconf configuration.
        ZEROCONF_XPATH="/config/services/zeroconf/services"

        if ! omv_config_exists "${ZEROCONF_XPATH}/service[id='transmissionbt']"; then
            zeroconf=""

            zeroconf="${zeroconf}<id>transmissionbt</id>"
            zeroconf="${zeroconf}<enable>1</enable>"
            zeroconf="${zeroconf}<name>%h - BitTorrent</name>"

            omv_config_add_node_data "${ZEROCONF_XPATH}" "service" "${zeroconf}"
        fi

        # Migrations.
        if dpkg --compare-versions "$2" lt-nl "3.0.5"; then
            omv_config_rename "${SERVICE_XPATH}/modules/filesandlocations/download.sharedfolderref" "download-sharedfolderref"
            omv_config_rename "${SERVICE_XPATH}/modules/filesandlocations/incomplete.sharedfolderref" "incomplete-sharedfolderref"
            omv_config_rename "${SERVICE_XPATH}/modules/filesandlocations/watch.sharedfolderref" "watch-sharedfolderref"
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
